<?php
/**
 * SomeController.php
 */

namespace bitsandbytes\ticketmaster\controllers;

use craft\web\Controller;

/**
 * SomeController
 *
 * @copyright   2020 UniWeb bvba
 * @license     http://framework.uniweb.eu/license
 * @link        http://docs.uniweb.be/application-framework
 * @since       2020-07-19 19:07
 * @author      pieterjangeeroms
 */
class SomeController extends Controller
{

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}