contentColumnType: boolean
fieldGroup: 3f9c4022-63a3-43ec-b68f-9257d269dc2f
handle: featured
instructions: 'Show on the homepage.'
name: Featured
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
