fieldLayouts:
  aabe8e44-3478-47e9-8c44-fa6f33211143:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 4692033e-4b14-49b0-a854-7650bfbdee3f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 53213477-b83c-443c-8c18-8e964348dd10
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: General
        sortOrder: 1
handle: contact
hasTitleField: false
name: Contact
section: c727393a-1637-4fb9-8a1f-fe3652d7acdd
sortOrder: 1
titleFormat: '{section.name|raw}'
